#!/usr/bin/env bash
#
# anima-web one-click setup script (Linux / macOS)
#
# Usage:
#   chmod +x setup.sh
#   ./setup.sh
#   ./setup.sh --skip-electron
#   ./setup.sh --openclaw-url "http://127.0.0.1:18789/v1/chat/completions" \
#              --openclaw-token "mytoken" \
#              --openclaw-agent "main"

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
SKIP_ELECTRON=false
OPENCLAW_URL=""
OPENCLAW_TOKEN=""
OPENCLAW_AGENT="main"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --skip-electron)   SKIP_ELECTRON=true; shift ;;
    --openclaw-url)    OPENCLAW_URL="$2"; shift 2 ;;
    --openclaw-token)  OPENCLAW_TOKEN="$2"; shift 2 ;;
    --openclaw-agent)  OPENCLAW_AGENT="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

step()  { echo -e "\n\033[36m=== $1 ===\033[0m"; }
ok()    { echo -e "  \033[32m[OK]\033[0m $1"; }
warn()  { echo -e "  \033[33m[WARN]\033[0m $1"; }
err()   { echo -e "  \033[31m[ERROR]\033[0m $1"; }

# ─────────────────────────────────────────────────────────
# 1. Check prerequisites
# ─────────────────────────────────────────────────────────
step "Checking prerequisites"

if ! command -v node &>/dev/null; then
  err "Node.js is not installed. Please install Node.js >= 18 from https://nodejs.org"
  exit 1
fi
ok "Node.js $(node --version)"
ok "npm $(npm --version)"

PYTHON_BIN=""
for bin in python3 python; do
  if command -v "$bin" &>/dev/null && "$bin" --version 2>&1 | grep -q "Python 3"; then
    PYTHON_BIN="$bin"
    break
  fi
done
if [ -z "$PYTHON_BIN" ]; then
  err "Python 3 is not installed. Please install Python >= 3.9"
  exit 1
fi
ok "$($PYTHON_BIN --version) (command: $PYTHON_BIN)"

# ─────────────────────────────────────────────────────────
# 2. Install frontend dependencies
# ─────────────────────────────────────────────────────────
step "Installing frontend dependencies"
cd "$PROJECT_ROOT"
npm install
ok "Frontend dependencies installed"

# ─────────────────────────────────────────────────────────
# 3. Build frontend
# ─────────────────────────────────────────────────────────
step "Building frontend"
cd "$PROJECT_ROOT"
npm run build
ok "Frontend built -> dist/"

# ─────────────────────────────────────────────────────────
# 4. Install Python dependencies
# ─────────────────────────────────────────────────────────
step "Installing Python dependencies"
cd "$PROJECT_ROOT/server"
"$PYTHON_BIN" -m pip install -r requirements.txt --quiet
ok "Python dependencies installed"

# ─────────────────────────────────────────────────────────
# 5. Generate server/.env (if not exists)
# ─────────────────────────────────────────────────────────
step "Configuring server environment"
SERVER_ENV="$PROJECT_ROOT/server/.env"

if [ ! -f "$SERVER_ENV" ]; then
  cat > "$SERVER_ENV" << ENVEOF
# anima-web server configuration
# Generated by setup.sh on $(date '+%Y-%m-%d %H:%M:%S')

ANIMA_HOST=0.0.0.0
ANIMA_PORT=19000
ANIMA_API_BASE_URL=https://sumi-test.sumeruai.com
ENVEOF

  if [ -n "$OPENCLAW_URL" ]; then
    cat >> "$SERVER_ENV" << ENVEOF

# OpenClaw configuration
OPENCLAW_API_URL=$OPENCLAW_URL
OPENCLAW_TOKEN=$OPENCLAW_TOKEN
OPENCLAW_DEFAULT_AGENT=$OPENCLAW_AGENT
ENVEOF
  else
    cat >> "$SERVER_ENV" << ENVEOF

# OpenClaw configuration (uncomment and fill in to enable)
# OPENCLAW_API_URL=http://127.0.0.1:18789/v1/chat/completions
# OPENCLAW_TOKEN=your-token-here
# OPENCLAW_DEFAULT_AGENT=main
ENVEOF
  fi
  ok "Created server/.env"
else
  warn "server/.env already exists, skipping"
fi

# ─────────────────────────────────────────────────────────
# 6. Electron packaging (optional)
# ─────────────────────────────────────────────────────────
if [ "$SKIP_ELECTRON" = false ] && [ -f "$PROJECT_ROOT/electron-shell/package.json" ]; then
  step "Installing Electron dependencies"
  cd "$PROJECT_ROOT/electron-shell"
  npm install
  ok "Electron dependencies installed"

  step "Packaging Electron app"
  npm run make
  ok "Electron app packaged"

  if [ -d "$PROJECT_ROOT/electron-shell/out" ]; then
    ok "Output: $PROJECT_ROOT/electron-shell/out"
  fi
else
  if [ "$SKIP_ELECTRON" = true ]; then
    warn "Electron packaging skipped (--skip-electron)"
  fi
fi

# ─────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────
echo ""
echo -e "\033[32m========================================\033[0m"
echo -e "\033[32m  Setup complete!\033[0m"
echo -e "\033[32m========================================\033[0m"
echo ""
echo "  To run the server:"
echo "    cd server && $PYTHON_BIN app.py"
echo ""
echo "  To run Electron (dev mode):"
echo "    cd electron-shell && npm start"
echo ""
if [ -z "$OPENCLAW_URL" ]; then
  echo -e "  \033[33mTo enable OpenClaw, edit server/.env\033[0m"
fi
