<#
.SYNOPSIS
    anima-web one-click setup script (Windows PowerShell)
.DESCRIPTION
    Downloads dependencies, builds the frontend, configures the server,
    and optionally packages as an Electron installer.
.PARAMETER SkipElectron
    Skip Electron packaging step.
.PARAMETER OpenClawUrl
    OpenClaw API endpoint URL.
.PARAMETER OpenClawToken
    OpenClaw bearer token.
.PARAMETER OpenClawAgent
    Default OpenClaw agent name.
.EXAMPLE
    .\setup.ps1
    .\setup.ps1 -OpenClawUrl "http://127.0.0.1:18789/v1/chat/completions" -OpenClawToken "mytoken"
    .\setup.ps1 -SkipElectron
#>

param(
    [switch]$SkipElectron,
    [string]$OpenClawUrl = "",
    [string]$OpenClawToken = "",
    [string]$OpenClawAgent = "main"
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $MyInvocation.MyCommand.Definition

function Write-Step { param([string]$msg) Write-Host "`n=== $msg ===" -ForegroundColor Cyan }
function Write-Ok   { param([string]$msg) Write-Host "  [OK] $msg" -ForegroundColor Green }
function Write-Warn { param([string]$msg) Write-Host "  [WARN] $msg" -ForegroundColor Yellow }
function Write-Err  { param([string]$msg) Write-Host "  [ERROR] $msg" -ForegroundColor Red }

# ─────────────────────────────────────────────────────────
# 1. Check prerequisites
# ─────────────────────────────────────────────────────────
Write-Step "Checking prerequisites"

$nodeVersion = $null
try { $nodeVersion = (node --version 2>&1) } catch {}
if (-not $nodeVersion) {
    Write-Err "Node.js is not installed. Please install Node.js >= 18 from https://nodejs.org"
    exit 1
}
Write-Ok "Node.js $nodeVersion"

$npmVersion = $null
try { $npmVersion = (npm --version 2>&1) } catch {}
Write-Ok "npm $npmVersion"

$pythonBin = $null
foreach ($bin in @("python", "python3")) {
    try {
        $ver = & $bin --version 2>&1
        if ($ver -match "Python 3") { $pythonBin = $bin; break }
    } catch {}
}
if (-not $pythonBin) {
    Write-Err "Python 3 is not installed. Please install Python >= 3.9 from https://python.org"
    exit 1
}
$pyVer = & $pythonBin --version 2>&1
Write-Ok "$pyVer (command: $pythonBin)"

# ─────────────────────────────────────────────────────────
# 2. Install frontend dependencies
# ─────────────────────────────────────────────────────────
Write-Step "Installing frontend dependencies"
Push-Location $ProjectRoot
npm install
if ($LASTEXITCODE -ne 0) { Write-Err "npm install failed"; exit 1 }
Write-Ok "Frontend dependencies installed"
Pop-Location

# ─────────────────────────────────────────────────────────
# 3. Build frontend
# ─────────────────────────────────────────────────────────
Write-Step "Building frontend"
Push-Location $ProjectRoot
npm run build
if ($LASTEXITCODE -ne 0) { Write-Err "npm run build failed"; exit 1 }
Write-Ok "Frontend built -> dist/"
Pop-Location

# ─────────────────────────────────────────────────────────
# 4. Install Python dependencies
# ─────────────────────────────────────────────────────────
Write-Step "Installing Python dependencies"
Push-Location "$ProjectRoot\server"
& $pythonBin -m pip install -r requirements.txt --quiet
if ($LASTEXITCODE -ne 0) { Write-Err "pip install failed"; exit 1 }
Write-Ok "Python dependencies installed"
Pop-Location

# ─────────────────────────────────────────────────────────
# 5. Generate server/.env (if not exists)
# ─────────────────────────────────────────────────────────
Write-Step "Configuring server environment"
$serverEnvPath = Join-Path $ProjectRoot "server\.env"

if (-not (Test-Path $serverEnvPath)) {
    $envLines = @(
        "# anima-web server configuration",
        "# Generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')",
        "",
        "ANIMA_HOST=0.0.0.0",
        "ANIMA_PORT=19000",
        "ANIMA_API_BASE_URL=https://sumi-test.sumeruai.com"
    )

    if ($OpenClawUrl) {
        $envLines += ""
        $envLines += "# OpenClaw configuration"
        $envLines += "OPENCLAW_API_URL=$OpenClawUrl"
        $envLines += "OPENCLAW_TOKEN=$OpenClawToken"
        $envLines += "OPENCLAW_DEFAULT_AGENT=$OpenClawAgent"
    } else {
        $envLines += ""
        $envLines += "# OpenClaw configuration (uncomment and fill in to enable)"
        $envLines += "# OPENCLAW_API_URL=http://127.0.0.1:18789/v1/chat/completions"
        $envLines += "# OPENCLAW_TOKEN=your-token-here"
        $envLines += "# OPENCLAW_DEFAULT_AGENT=main"
    }

    $envLines -join "`n" | Set-Content -Path $serverEnvPath -Encoding UTF8 -NoNewline
    Write-Ok "Created server/.env"
} else {
    Write-Warn "server/.env already exists, skipping"
}

# ─────────────────────────────────────────────────────────
# 6. Electron packaging (optional)
# ─────────────────────────────────────────────────────────
if (-not $SkipElectron) {
    $electronDir = Join-Path $ProjectRoot "electron-shell"
    if (Test-Path (Join-Path $electronDir "package.json")) {
        Write-Step "Installing Electron dependencies"
        Push-Location $electronDir
        npm install
        if ($LASTEXITCODE -ne 0) { Write-Err "Electron npm install failed"; exit 1 }
        Write-Ok "Electron dependencies installed"

        Write-Step "Packaging Electron app"
        npm run make
        if ($LASTEXITCODE -ne 0) { Write-Err "Electron make failed"; exit 1 }
        Write-Ok "Electron app packaged"

        $outDir = Join-Path $electronDir "out"
        if (Test-Path $outDir) {
            Write-Ok "Output: $outDir"
            $installers = Get-ChildItem -Path $outDir -Recurse -Include "*.exe","*.msi","*.Setup.exe" | Select-Object -ExpandProperty FullName
            if ($installers) {
                Write-Host ""
                Write-Host "  Installer(s) found:" -ForegroundColor Green
                foreach ($f in $installers) {
                    Write-Host "    $f" -ForegroundColor White
                }
            }
        }
        Pop-Location
    } else {
        Write-Warn "electron-shell/package.json not found, skipping Electron packaging"
    }
} else {
    Write-Warn "Electron packaging skipped (-SkipElectron)"
}

# ─────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────
Write-Host ""
Write-Host "========================================" -ForegroundColor Green
Write-Host "  Setup complete!" -ForegroundColor Green
Write-Host "========================================" -ForegroundColor Green
Write-Host ""
Write-Host "  To run the server:" -ForegroundColor White
Write-Host "    cd server && $pythonBin app.py" -ForegroundColor Gray
Write-Host ""
Write-Host "  To run Electron (dev mode):" -ForegroundColor White
Write-Host "    cd electron-shell && npm start" -ForegroundColor Gray
Write-Host ""
if (-not $OpenClawUrl) {
    Write-Host "  To enable OpenClaw, edit server/.env" -ForegroundColor Yellow
}
